# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: auth-server


#provider: declaration
  #name: Your provider name (aws, google, azure, etc.)
  #runtime: A runtime supported by your provider (e.g., with AWS, you can use “nodejs12.x”, but for Google, you’d need to use “nodejs”)
  #region: The region in which you want your functions to be hosted
    #<other_option>: <value>
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  timeout: 60 
  lambdaHashingVersion: 20201221
#timeout default is 6 seconds, but because of the “cold start” that serverless functions suffer from, six seconds isn’t always enough to initialize and execute a function
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    PROJECT_ID: ${file(config.json):PROJECT_ID}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}


functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get    

